name: Github Actions Demo
on: [push]
jobs:
  Golang-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.3'
      - run: go version
      - run: go test ./...
      - name: Discord notification by failure test
        if: ${{ failure() }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: 'Github Bot'
          DISCORD_AVATAR : https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
        uses: Ilshidur/action-discord@0.3.0
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been failed test.'